<?php
	class UserAction extends Action{
		function index(){
			if($_SESSION['uid']){
				$info=D('User')->find($_SESSION['uid']);
				redirect(U('Ondo/index'));
			}else{
				$this->error("请先登入","/index.php/User/login");
			}
		}
		function login(){
			if($_SESSION['uid']){
				$this->error("你已经登入","/index.php/User");
			}
			if($_POST){
				$pass=$_POST['pass'];
				$name=$_POST['name'];
				$re=D('User')->login($name,$pass);
				if($re['status']){
					$this->success($re['con'],"/index.php/User");
				}else{
					$this->error($re['con']);
				}
			}else{
				$this->display();
			}
		}
		function pass(){
			if($_SESSION['uid']){
				$old=trim($_POST['old']);
				$new_pass=trim($_POST['new']);
				if(strlen($new_pass)<=3){
					$this->error("密码必须大于3位！");
					return;
				}
				if($old&&$new_pass){
					$re=D('User')->pass_change($old,$new_pass);
					if($re['status']){
						$this->success($re['con']);
					}else{
						$this->error($re['con']);
					}
					return;
				}else{
					$this->error("密码为空");
					return;
				}
			}else{
				$this->error("你尚未登入！");
				return;
			}
		}
		function join(){
			if($_SESSION['uid']){
				$this->error("你已经登入","/index.php/User");
			}
			if($_POST){
				if($_POST['checkbox']!="t"){
					$this->error("未同意服务条款！");
				}
				$yzm=trim($_POST['verify']);
				$jugg_yzm=md5($yzm);
				if($jugg_yzm!=$_SESSION['verify']){
					$this->error("验证码错误！");
				}
				if(strlen($_POST['name'])<=3||strlen($_POST['pass'])<=6){
					$this->error("用户名必须大于3位，密码必须大于6位！");
				}
				if(strlen($_POST['name'])>16){
					$this->error("用户名不得大于16个字节");
				}
				$code=@strtolower($_POST['code']);
				$code=@trim($code);
				$jugg_code=D('Code')->jugg($code);
				if(!$jugg_code['status']){
					$this->error($jugg_code['con']);
				}
				$email=$_POST['email'];
				$pass=$_POST['pass'];
				$name=$_POST['name'];
				$re=D('User')->join($name,$pass,$email);
				if($re['status']){
					D('Code')->add_uid($code);
					$this->success($re['con'],"/index.php/User");
				}else{
					$this->error($re['con']);
				}
			}else{
				$site=D('Site')->find(1);
       			$this->assign("site",$site);
				$this->display();
			}
		}
		function logout(){
			$re=D('User')->logout();
			if($re['status']){
				$this->success($re['con'],"/index.php/User/login");
			}else{
				$this->error($re['con'],"/index.php/User/login");
			}

		}
	}